services:
  frontend:
    build:
      context: ./EA-Task-Tracker-frontend
      dockerfile: Dockerfile
    container_name: ea_tracker_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - ea_network

networks:
  ea_network:
    name: ea_network
    external: true



    