services:
  db:
    extends:
      file: docker-compose.db.yml
      service: db

  backend:
    extends:
      file: docker-compose.backend.yml
      service: backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    extends:
      file: docker-compose.frontend.yml
      service: frontend
    depends_on:
      - backend

volumes:
  mysql_data:
    name: ea_tracker_mysql_data
  static_volume:
    name: ea_tracker_static_volume
  media_volume:
    name: ea_tracker_media_volume

networks:
  ea_network:
    name: ea_network
    driver: bridge