# Generated by Django 5.2.9 on 2026-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quarter',
            field=models.CharField(choices=[('Q3_2025', 'Q3 2025'), ('Q4_2025', 'Q4 2025'), ('Q1_2026', 'Q1 2026'), ('Q2_2026', 'Q2 2026'), ('Q3_2026', 'Q3 2026'), ('Q4_2026', 'Q4 2026'), ('Q1_2027', 'Q1 2027'), ('Q2_2027', 'Q2 2027')], db_index=True, default='Q1_2026', max_length=10),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['quarter'], name='tasks_quarter_f244cc_idx'),
        ),
    ]
